### ISSUE TITLE
MacBook Air doesn't show Skybox star field (MB Pro is fine)

### ISSUE THREAD

**Issue by shentonfreude** [koansys/isat#109]
Confirmed on Josh and Bre's MBAs.

Query into Cesium-dev
https://groups.google.com/forum/?hl=en&fromgroups=#!topic/cesium-dev/3sQT5CxzNhg

**Comment by shentonfreude** [comment]
Appears to be a problem with Mac hardware and drivers: long discussion at:
https://groups.google.com/forum/?hl=en&fromgroups=#!topic/cesium-dev/NU-d53X8mj4

**Comment by joshfinnie** [comment]
Updated in the latest Cesium. Not an iSat issue...
