### ISSUE TITLE
Cronjob to pull TLEs from Celestrak to server, produce artifacts

### ISSUE THREAD

**Issue by shentonfreude** [koansys/isat#111]
For s.n.g we'll need a cronjob that pulls TLE files from Celestrak daily, like we do for the olde JTrack3D.  

In that, we'll need to produce artifacts, like a distinct file containing only Science Missions.  Perhaps also the requested "All" satellites file as well (with de-duping).

We might even want to generate a file for searches that lists the satellite name and corresponding file that they live in, but that's probably a post-1.0 feature in the UI and app itself.

**Comment by shentonfreude** [comment]
This includes things like the just-launched Landsat 8.

**Comment by joshfinnie** [comment]
Must have HST.

**Comment by shentonfreude** [comment]
Josh, .../isat/tle-utils/get_celestrak_files.py no retrieves those files and saves a copy of each under viz/tle/.
It then generates an ALL.txt of the combined, deduped, alphabetized satellites there -- including HST.
And generates an SMD.txt of the ones for which we have Science Mission NORAD IDs.
That's the only stuff that should go int the viz/tle/ dir -- I've removed my old crap.

I've run out of time to wrap this in a cron job -- I'll need to work with you to figure out the target directory for them. And we'll have to be _super_ careful we don't overwrite good files with bad ones (e.g., empty files) or run amok nuking files if we have a failure getting to Celestrak.   

So before you deploy again to get the math corrections, run get_celestrak_files.py and commit first to bring us up to date.
