### ISSUE TITLE
Open Street map renders in at different stages as user zooms

### ISSUE THREAD

**Issue by colleenkaiser** [koansys/isat#112]
see attached image - as the user zooms in and out different parts of the globe render at different rates so you might see more detail in one section of the globe than in another.
![globe-drawing-in](https://f.cloud.github.com/assets/571317/97908/b7993f86-670c-11e2-86d6-61176530194e.gif)

**Comment by shentonfreude** [comment]
Nothing I can we about that :-(
#WontFix

(oh, this is great, first time I'm seeing the geo-location icon beyond the DC area!)
