### ISSUE TITLE
Add atmosphere around globe to help visualization

### ISSUE THREAD

**Issue by shentonfreude** [koansys/isat#113]
Jenny's comp adds an atmosphere so that the globe doesn't get lost in the black void of space.

**Comment by colleenkaiser** [comment]
Are you referring to the green bands that fade in?  I like them but I think they'll obscure the remote satellite icons and the globe as the user zooms.

**Comment by shentonfreude** [comment]
Fixed in [e2a6adf84f61999283bdf333d01a11d330a7881c]

Colleen, see sot.koansys.com/viz for latest update with atmosphere: the sky seen from space.
Sorry, I wasn't clear
