### ISSUE TITLE
Port js to AMD and make it a library

### ISSUE THREAD

**Issue by reedobrien** [koansys/isat#162]
Files TODO:
- [x] angl.js
- [x] ~~compat.js~~ _for UI not available in lib_
- [x] constastro.js
- [x] constmath.js
- [x] days2mdh.js
- [x] dpper.js
- [x] dscom.js
- [x] dsinit.js
- [x] dspace.js
- [x] getgravc.js
- [x] gstime.js
- [x] initl.js
- [x] invjday.js
- [x] ~~isat.js~~ _Nope app not lib_
- [x] ~~isat.min.js~~ _Nope app not lib_
- [x] jday.js
- [x] mag.js
- [x] math_utils.js
- [x] newtonnu.js
- [ ] ~~qunit.js~~ _nope not part of lib_
- [x] rv2coe.js
- [x] sgp4init.js
- [x] sgp4.js
- [ ] ~~**sprintf.js** _TODO:_ Do I need this? cli only not useful for lib~~
- [x] twoline2rv.js

**Comment by davidcalhoun** [comment]
If there's any libraries that could also work on the server (like the SGP4 stuff), it would be nice to have a UMD wrapper for those: https://github.com/umdjs/umd

It's super ugly, but in the end supports CommonJS (Node.js and Browserify), AMD (RequireJS), and older environments where those aren't available (no module loader, so it becomes defined in the global scope).

I wrote up a quick overview that hopefully helps: http://davidbcalhoun.com/2014/what-is-amd-commonjs-and-umd/

**Comment by joshfinnie** [comment]
@reedobrien, check out this repo: https://github.com/koansys/sgp4lib

Might help you get on with this task!

**Comment by reedobrien** [comment]
Do we need global opsmode? See #163

**Comment by reedobrien** [comment]
Just need docco on twoline2rv.js and sgp4init.js and then we can promote it out of this repo.
