### ISSUE TITLE
Show orbit track for selected satellite(s)

### ISSUE THREAD

**Issue by shentonfreude** [koansys/isat#38]

**Comment by shentonfreude** [comment]
TLE line 2 tells us revolutions per day, so we can figure out how much time we need to walk to show one complete revolution trail

53–63 Mean Motion [Revs per day]  15.72125391

Can we find how "big" the ellipse is, so we can calculate how many segments we'll have to render to show a smooth curve?

**Comment by Alex-developer** [comment]
Adding to this a small tip ....

When building the pollyline also create a second when the sat el is above the observers location. Set this polyline to green and you will get something like the image below

Alex

![Screen Shot 2012-12-19 at 17 10 04](https://f.cloud.github.com/assets/3010165/22465/16e07908-49ff-11e2-8588-1ec8a2a68ce8.png)

**Comment by Alex-developer** [comment]
Re commit 6a97be1 "We could put any number of individual orbit traces (e.g., 10 different
satellite orbits) into the orbitTraces colleciton but only one is
stored at present. We'd have to determine a different way of
enabling/disabling individual traces, perhaps storing a list of traced
satellites, perhaps attached to the collection itself."

Have a look at my code. I implemented a two state satellite selection process, its still not massively intuitive but I am working on it.

A satellite can have two states

Being displayed - Its showing on the various views. In the screenshot above any satellite in the 'Sat Selector' is 'being displayed'
Selected - Its orbit and footprint are being displayed. In the screenshot above any satellite that has its check box selected is 'selected'

Doing this When I want to plot the orbit lines I just grab a list of all 'selected' satellites and plot those.

Alex

**Comment by shentonfreude** [comment]
Sorry for not staying in contact with you the past couple weeks -- been out
of town for the holidays.
We've been tasked to get SOT integrated into science.nasa.gov and demo it
to the public the first week of March, so we're having to triage a lot of
our issues.

I'm looking forward to taking a look at your code!

**Comment by Alex-developer** [comment]
Not sure if you got the emails but the code is all on GitHub now

Alex

**Comment by Alex-developer** [comment]
Oh and no worries re contact I can see you are very busy :-)
