### ISSUE TITLE
If I zoom out "too far" globe disappears, calcs stop, I can't zoom in again -- frozen?

### ISSUE THREAD

**Issue by shentonfreude** [koansys/isat#48]
Zoom way out, view frustum presumably culls all the information. Try to zoom back in, you can't. Notice that the updates to the positions is frozen.

**Comment by joshfinnie** [comment]
Seems to be fixed? Could zoom back in after losing focus on earth.

**Comment by shentonfreude** [comment]
Not so sure: I thought that too, lost the globe, saw stats updating, but then zoomed out some more and saw them freeze.

Need more thorough testing.

**Comment by shentonfreude** [comment]
From the GitHub notifications, Tomdavid, Patrick Cozzi, Dan Bagnell say they see it at extreme zooms.

You can set minimumZoomDistance and maximumZoomDistance property on CameraController.   

Tomdavid points out that b11, that I'm using now, doesn't have a CameraController, and I can't find any similar attributes in the cesium code now.

**Comment by shentonfreude** [comment]
Sounds like AGI fixed this in Cesium, so update our Cesium.js code from their master

https://github.com/AnalyticalGraphicsInc/cesium/issues/319
