### ISSUE TITLE
UI improvement feedback

### ISSUE THREAD

**Issue by shentonfreude** [koansys/isat#75]
From educator Steve Hasselberg:

Rather than having a click on a satellite take you to the link, I might
suggest a different approach.  Select a single satellite by clicking on it.
The active satellite might show its name or be highlighted in some way.
Then click on different options (like a palette) to have it do different
things with that satellite: toggle track on/off, go to information page,
center the satellite, zoom to the satellite, fly over track, sighting
information, etc.

This is along the lines of something we've briefly discussed. No reason a pop-up couldn't show name, lat, lon, alt, velocity and click to turn on various other features: orbit, Science/NSSDC details.

**Comment by colleenkaiser** [comment]
I will wireframe.

**Comment by shentonfreude** [comment]
I'm now thinking that -- like other sites such as n2yo.com -- we keep the vitals on the page, not in a pop-up. This would allow you to watch a sat's info, but still interact with the globe: zoom in, spin around, etc. 

Wondering advantages of pop-up versus side/below display (chosen based on aspect ration -- landscape vs portrait -- of browser). Perhaps different info for each?
