### ISSUE TITLE
Support IE with ChromeFrame

### ISSUE THREAD

**Issue by shentonfreude** [koansys/isat#76]
Educator Darren Dootson says it doesn't work in IE:

  Hi, the tracker does not work on ie which is the default browser on our school network. The display is not rendered. 

Perhaps there's a shim we can load if we detect unsupported WebGL and use of IE? Maybe http://iewebgl.com/ or better, ChromeFrame. For the latter, looks like we have to detect, then tell them where/how to download it.

**Comment by joshfinnie** [comment]
Chrome Frame does not trigger WebGL support in Modernizr.
