### ISSUE TITLE
Use thumbnails for selecting Earth Views and Map Providers

### ISSUE THREAD

**Issue by colleenkaiser** [koansys/isat#84]
Thumbnails will provide users with a small preview of their options.  Users may not know what to expect in a 2.5-D view or what the difference is between Bing Maps and Open Street View.

I will mock up the menu for these.

**Comment by shentonfreude** [comment]
Colleen, check what the Cesium folks do with their widgets:
http://cesium.agi.com/Cesium/Build/Apps/CesiumViewer/
We can prolly steal them.
